apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: test-project
spec:
  type: ClusterIP
  selector:
    app: test-service-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80