apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test-service-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007