volumes:
  docker-image-registry:

services:
  docker-image-registry: 
    image: registry
    volumes:
      - docker-image-registry:/var/lib/registry
    ports:
      - 5000
    restart: always
  test-service: 
    build:
      context: ${ROOT_DIRECTORY}/projects/test-project/repos/test-service/src
      dockerfile: ${ROOT_DIRECTORY}/projects/test-project/repos/test-service/build/dockerfile
    ports:
      - 80
    restart: always
  proxy: 
    build:
      context: ${INFRASTRUCTURE_DIRECTORY}/proxy
      dockerfile: ${INFRASTRUCTURE_DIRECTORY}/proxy/dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
