services:
  docker-image-registry: 
    image: registry
    ports:
      - 5000
    restart: always
  test-service: 
    build:
      context: ${ROOT_DIRECTORY}/repos/test-service/src
      dockerfile: ${ROOT_DIRECTORY}/repos/test-service/build/dockerfile
    ports:
      - 80
    restart: always
  proxy: 
    build:
      context: ${INFRASTRUCTURE_DIRECTORY}/proxy
      dockerfile: ${INFRASTRUCTURE_DIRECTORY}/proxy/dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
